trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    # codeCoverageToolOption: 'JaCoCo'
    # codeCoverageClassFilesDirectories: '$(System.DefaultWorkingDirectory)/**/target/classes'
    # codeCoverageSourceDirectories: '$(System.DefaultWorkingDirectory)/**/src/main/java/'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    # sonarQubeRunAnalysis: true
    # isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
    checkStyleRunAnalysis: true